In [1]:
import uproot
import pandas as pd
import awkward as ak
import vector
import matplotlib.pyplot as plt
import os

import sys
sys.path.insert(0, '../utils/')

from utils import createDirs

luminosity_ifb = 10.

# Define out input and output paths, make sure the output path exists.
ntuple_path = "../data/GamGam/"
output_path = "../histograms/GamGam_pythonic/"
createDirs(output_path)

/histograms
..//histograms
/histograms/GamGam_pythonic
..//histograms/GamGam_pythonic
/histograms/GamGam_pythonic/
..//histograms/GamGam_pythonic/

#### Exercises: Read the function below. There are several "TODO" items to complete.

In [2]:
# now vectorially process each event, retrieve the needed info from the ntuple, check if the event passes our selection, and fill histograms for the output.
def eventProcessor (tree, out_hists, is_data, h5key):
    """
    Process events in a tree using uproot and awkward, apply some selections and return a flat pandas dataframe
    """

    # TODO include the scaleFactor_PHOTON in the event weight, and the photon_isTightID branch.
    branches = ["photon_pt", "photon_E", "photon_eta", "photon_phi", "photon_n", "mcWeight", "XSection", "SumWeights", "scaleFactor_PILEUP"]

    # Read in the TTree to an Awkward Array (allows for vectors of branch values for each event rather than a pandas dataframe which must strcitly tabular.)
    ## https://awkward-array.org/doc/main/ 

    df = pd.DataFrame()

    akdf = uproot.concatenate(tree, filter_name = branches, library='ak')

    # get an idea of what this object looks like:
    print(akdf)

    # Note the photons are stored in descending pT order

    # only care about photons that are in the fiducial region
    photon_eta_mask = (abs(akdf["photon_eta"]) < 2.37) & ((abs(akdf["photon_eta"]) < 1.37) | (abs(akdf["photon_eta"]) > 1.56))
    features_photon = ["photon_pt", "photon_E", "photon_eta", "photon_phi"]
    for pf in features_photon:
        akdf[pf] = akdf[pf][photon_eta_mask]
    del photon_eta_mask

   # TODO we're also only interested photons that have passed a Tight particle ID, to reduce misreconstruction backgrounds.
    # Can we add a similar mask to require that all the photons pass the Tight Identification? via the photon_isTightID bool variable.

    # Need events that have at least 2 photons in.
    nphoton_mask = ak.num(akdf['photon_pt']) >= 2
    akdf = akdf[nphoton_mask]
    del nphoton_mask

    # We need to apply the photon trigger requirements, approximated by requiring our photons to have photon 1(2) pT > 35(25) GeV
    photon1_pt = akdf.photon_pt[:, 0]
    photon2_pt = akdf.photon_pt[:, 1]
    photon_1_pt_mask = (photon1_pt > 35_000)
    photon_2_pt_mask = (photon2_pt > 25_000)
    photon_pt_mask = photon_1_pt_mask & photon_2_pt_mask
    akdf = akdf[photon_pt_mask]
    del photon_1_pt_mask
    del photon_2_pt_mask
    del photon_pt_mask


    # Only interested in events that have exactly 2 photons in that pass the requirements, to fill our pandas dataframe.
    nphoton_mask = ak.num(akdf['photon_pt']) == 2
    akdf = akdf[nphoton_mask]
    del nphoton_mask

    ak.drop_none(akdf)
    
    # Obtain the kinematic variables in our PANDAS dataframe (note TTree is in MeV and I want GeV)
    df["photon_1_pt"] = akdf["photon_pt"][:,0]*0.001
    df["photon_2_pt"] = akdf["photon_pt"][:,1]*0.001
    df["photon_1_E"] = akdf["photon_E"][:,0]*0.001
    df["photon_2_E"] = akdf["photon_E"][:,1]*0.001
    df["photon_1_eta"] = akdf["photon_eta"][:,0]
    df["photon_2_eta"] = akdf["photon_eta"][:,1]
    df["photon_1_phi"] = akdf["photon_phi"][:,0]
    df["photon_2_phi"] = akdf["photon_phi"][:,1]
        
    # read in the event weights
    if (is_data):
        df["histoweight"] = 1.0
    else:
        # MC event weighting to luminosity of data
        df["histoweight"] = akdf["mcWeight"] * akdf["XSection"]*1000. * luminosity_ifb / akdf["SumWeights"]
        # MC weight corrections for experimental effects
        df["histoweight"] *= akdf["scaleFactor_PILEUP"] # TODO multiply by the photon scale factor weight


    # TODO we're also only interested in the case where our two photons have passed a Tight particle ID, to reduce misreconstruction backgrounds.
    # Can you use the boolean "photon_isTightID" vector branch to require this?..

    photon_1_p4 = vector.arr( { 'pt' : df['photon_1_pt'],
                           'eta' : df['photon_1_eta'],
                           'phi' : df['photon_1_phi'],
                           'E': df['photon_1_E']
                           } )
    photon_2_p4 = vector.arr( { 'pt' : df['photon_2_pt'],
                           'eta' : df['photon_2_eta'],
                           'phi' : df['photon_2_phi'],
                           'E': df['photon_2_E']
                           } )
    
    diphoton_p4 = photon_1_p4 + photon_2_p4
    df["diphoton_mass"] = diphoton_p4.m

    # Another requirement for the events is a pT/diphoton mass bound (doing this in the dataframe to demonstrate how to filter pdframes)
    passRatio = (df['photon_1_pt']/df['diphoton_mass'] > 0.35) & (df['photon_2_pt']/df['diphoton_mass'] > 0.25)
    df["passEnergyRatio"] = passRatio
    df.query('passEnergyRatio', inplace=True)

    # Write out final selected data for further analysis
    df.to_hdf(out_hists +".h5", key=h5key, mode="w")
    df.to_csv(out_hists +".csv", mode="w")

    return df

In [3]:
# EventLoop analysis over the Data 

# write the file we will output our data histograms into (in .h5 and .csv format)
out_df_data_str = output_path+"data"

# read in our data ntuples
tree_data_str = ntuple_path+"/Data/data_*.GamGam.root:mini"

# loop over the data ntuple to process needed info into histograms
df_data = eventProcessor(tree_data_str, out_df_data_str, True, 'data')
df_data

[{mcWeight: 0, scaleFactor_PILEUP: 0, photon_n: 2, photon_pt: [...], ...}, ...]

,photon_1_pt,photon_2_pt,photon_1_E,photon_2_E,photon_1_eta,photon_2_eta,photon_1_phi,photon_2_phi,histoweight,diphoton_mass,passEnergyRatio
1,60.888741,37.795013,61.814072,56.970108,0.174119,-0.968964,1.859500,-0.888251,1.0,110.461632,True
2,39.186214,25.327362,39.567226,50.309616,0.139337,-1.309055,1.016534,-1.787857,1.0,79.565292,True
3,35.529690,29.579599,56.908459,57.963634,1.048340,1.293301,1.587437,-1.533586,1.0,65.320351,True
4,48.605839,29.717976,53.581547,31.570139,-0.448705,0.351249,0.719785,2.904021,1.0,74.342133,True
5,64.788353,52.240429,81.901268,163.913956,0.711707,1.810213,2.959962,-0.116647,1.0,134.297394,True
...,...,...,...,...,...,...,...,...,...,...,...
7105496,104.492874,65.215431,325.386932,84.647697,-1.802203,-0.753985,0.313434,-2.046192,1.0,177.477020,True
7105497,42.760803,29.416094,58.098064,31.302219,-0.823499,-0.356217,2.304370,-0.768865,1.0,72.837067,True
7105498,56.330582,27.199383,56.901821,32.148697,-0.142294,-0.594473,-2.986454,0.670651,1.0,77.775566,True
7105500,72.873672,45.556427,107.191780,56.051189,0.935952,-0.666378,3.046246,0.610477,1.0,149.009415,True
7105501,41.198303,39.577068,43.213573,66.560402,0.311521,1.109877,-0.288351,1.504822,1.0,71.245026,True

In [4]:
# EventLoop analysis over the signal MC ntuples gluon gluon fusion -> H -> gamma gamma

# write the file we will output our processed ggf Higgs events into (in .h5 and .csv format)
out_df_ggfHiggs_str = output_path+"ggfHiggs"

# read in our ggfHiggs ntuples
tree_ggfHiggs_str = ntuple_path+"/MC/mc_343981.ggH125_gamgam.GamGam.root:mini"

# loop over the ggfHiggs ntuple to process needed info into histograms
df_ggf = eventProcessor(tree_ggfHiggs_str, out_df_ggfHiggs_str, False, 'ggfHiggs')
df_ggf

[{mcWeight: 28.5, scaleFactor_PILEUP: 0, photon_n: 2, photon_pt: ..., ...}, ...]

,photon_1_pt,photon_2_pt,photon_1_E,photon_2_E,photon_1_eta,photon_2_eta,photon_1_phi,photon_2_phi,histoweight,diphoton_mass,passEnergyRatio
0,58.376011,56.773354,65.302315,57.806873,-0.482442,0.190522,0.802856,-2.473249,0.000000,121.471718,True
1,68.964722,66.471428,238.266098,329.922729,1.911305,2.284927,-0.928285,3.092725,0.000183,125.145790,True
2,82.018768,69.614159,128.987595,121.158180,1.024764,1.152115,-2.291243,2.038926,0.000288,125.583717,True
3,60.740158,57.999924,60.790085,73.122002,-0.040543,0.707281,2.346246,-0.823392,0.000322,127.093018,True
4,75.291000,55.593014,75.340698,57.959332,-0.036332,0.290745,-3.027492,0.818152,0.000322,123.304176,True
...,...,...,...,...,...,...,...,...,...,...,...
939535,86.571335,43.302395,247.857681,207.190002,1.713036,2.247472,2.288404,-1.007161,0.000650,126.501854,True
939536,64.243874,59.020187,76.400284,62.364948,0.605870,0.335094,1.018733,-2.249694,0.000631,124.038437,True
939537,62.599831,62.278881,75.411896,73.880775,-0.629353,-0.601293,-0.726319,2.435065,0.000686,124.884476,True
939538,80.016304,52.876263,80.715851,57.308094,0.132135,0.406620,-2.955298,-0.205212,0.000686,128.857895,True
939539,115.103333,33.091393,129.285904,45.808895,0.491458,0.850819,-1.802522,1.392690,0.000686,125.387314,True

In [5]:
# EventLoop analysis over the signal MC ntuples Vector-boson fusion -> H -> gamma gamma

# write the file we will output our processed VBF Higgs events into (in .h5 and .csv format)
out_df_vbfHiggs_str = output_path+"vbfHiggs"

# read in our vbfHiggs ntuples
tree_vbfHiggs_str = ntuple_path+"/MC/mc_345041.VBFH125_gamgam.GamGam.root:mini"

# loop over the vbfHiggs ntuple to process needed info into histograms
df_vbf = eventProcessor(tree_vbfHiggs_str, out_df_vbfHiggs_str, False, 'vbfHiggs')
df_vbf

[{mcWeight: 3.75, scaleFactor_PILEUP: 0, photon_n: 2, photon_pt: ..., ...}, ...]

,photon_1_pt,photon_2_pt,photon_1_E,photon_2_E,photon_1_eta,photon_2_eta,photon_1_phi,photon_2_phi,histoweight,diphoton_mass,passEnergyRatio
0,76.868210,46.170959,78.347847,64.013298,-0.195896,-0.853037,-2.444054,0.680431,0.000000e+00,125.633766,True
1,79.918510,72.685318,147.984970,128.432632,-1.226758,-1.170541,1.101823,3.054119,2.716794e-07,126.339264,True
4,60.144890,40.534061,62.147934,77.002548,0.257373,-1.257010,0.628912,-3.068330,5.749620e-05,125.549889,True
5,76.805199,56.483429,244.681274,221.194382,-1.826235,-2.041526,-3.124200,0.756373,5.749620e-05,123.658867,True
6,177.419540,87.564232,217.907776,89.588768,-0.663353,-0.214625,-1.552290,-2.436178,6.856552e-05,120.617065,True
...,...,...,...,...,...,...,...,...,...,...,...
439908,56.288536,45.325504,70.362915,54.074001,0.693200,-0.611730,-0.813033,1.739113,1.620362e-04,119.754753,True
439909,142.445450,39.854725,147.092255,48.992233,0.254739,0.664844,-2.178687,-0.313203,5.537521e-05,124.981064,True
439910,75.344986,51.030186,141.041748,127.581200,-1.239651,-1.566848,1.314189,-1.962165,8.677970e-05,125.399643,True
439911,65.130150,63.108433,115.110199,90.046631,1.170829,0.893904,-1.114289,1.674922,1.009320e-04,127.487793,True
439912,60.644909,42.075291,64.605942,225.500290,0.359489,2.363189,-0.809405,-1.927940,1.009320e-04,130.529922,True

In [6]:
# Will be useful to also have a combined signal MC dataframe
df_allHiggs = pd.concat([df_vbf,df_ggf])
df_allHiggs.to_csv(output_path+'allHiggs.csv')
df_allHiggs

,photon_1_pt,photon_2_pt,photon_1_E,photon_2_E,photon_1_eta,photon_2_eta,photon_1_phi,photon_2_phi,histoweight,diphoton_mass,passEnergyRatio
0,76.868210,46.170959,78.347847,64.013298,-0.195896,-0.853037,-2.444054,0.680431,0.000000e+00,125.633766,True
1,79.918510,72.685318,147.984970,128.432632,-1.226758,-1.170541,1.101823,3.054119,2.716794e-07,126.339264,True
4,60.144890,40.534061,62.147934,77.002548,0.257373,-1.257010,0.628912,-3.068330,5.749620e-05,125.549889,True
5,76.805199,56.483429,244.681274,221.194382,-1.826235,-2.041526,-3.124200,0.756373,5.749620e-05,123.658867,True
6,177.419540,87.564232,217.907776,89.588768,-0.663353,-0.214625,-1.552290,-2.436178,6.856552e-05,120.617065,True
...,...,...,...,...,...,...,...,...,...,...,...
939535,86.571335,43.302395,247.857681,207.190002,1.713036,2.247472,2.288404,-1.007161,6.501487e-04,126.501854,True
939536,64.243874,59.020187,76.400284,62.364948,0.605870,0.335094,1.018733,-2.249694,6.308157e-04,124.038437,True
939537,62.599831,62.278881,75.411896,73.880775,-0.629353,-0.601293,-0.726319,2.435065,6.863188e-04,124.884476,True
939538,80.016304,52.876263,80.715851,57.308094,0.132135,0.406620,-2.955298,-0.205212,6.863188e-04,128.857895,True
939539,115.103333,33.091393,129.285904,45.808895,0.491458,0.850819,-1.802522,1.392690,6.863188e-04,125.387314,True